### ISSUE TITLE
Bug when publishing the LinkedTV core ontology

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/ontologies#1]
At the moment, you seem to redirect http://data.linkedtv.eu/ontologies/core to http://data.linkedtv.eu/ontologies/core/ (pay attention to the trailing slash).

Consequently, the LinkedTV ontology concepts and properties are identified with URI such as http://data.linkedtv.eu/ontologies/core/#Entity instead of course of http://data.linkedtv.eu/ontologies/core#Entity (pay attention to the trailing slash).

Could you please fix this? Since, in the RDF data, we use the later, not the former.

**Comment by alisarioglu** [comment]
Fixed
