### ISSUE TITLE
Add a new motivation scheme for representing the various dimensions in which an enrichment can be classified to

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/ontologies#7]
Background information at https://github.com/linkedtv/wp2/issues/18.

Per [definition](http://www.w3.org/ns/oa#d4e555), each Annotation SHOULD have at least one oa:motivatedBy relationship to an instance of oa:Motivation, which is a subClass of skos:Concept. A number of pre-existing motivations have been registered in the [oa:motivationScheme](motivationScheme). So far, we adopted the generic oa:linking motivation for ALL our enrichments. One possibility could be to create new skos:Concept in an extended motivationScheme, adapted to LinkedTV.

**Comment by lyndonnixon** [comment]
yes, although my feeling had been more to define a new class Dimension with members like inDepth, opinion etc. and associate Annotations with a linking motivation to a dimension with a property hasDimension. Then we don't mix dimensions up with motivations (for me, dimensions are more like scopes but in the OAM scopes seem to be understood in a different way)

**Comment by michielhildebrand** [comment]
Shall we just start with using oa:motivatedBy and add dimensions to the MotivationScheme. We need something quick to get going.

**Comment by lyndonnixon** [comment]
I'd wish to keep the backwards compatibility to "OAM-conform" models with oa:linking and of course we can't subclass instances...we could subclass oa:Motivation to an oax:Dimension and there define new instances (for each enrichment dimension) oax:timeline oax:indepth etc. Then we can at least owl:sameAs our new instances with oa:linking. oax: being of course our own namespace for LinkedTV-motivated OAM extensions (http://linkedtv.eu/ontologies/annotation ?)

**Comment by rtroncy** [comment]
This has been resolved differently. In the model, the `oa:linking` motivation is always used.
